# Generated by Django 3.0.3 on 2020-02-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('created_at', models.CharField(max_length=1000)),
                ('text', models.CharField(max_length=5000)),
                ('user_name', models.CharField(max_length=500)),
                ('user_screenname', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('url', models.CharField(max_length=2048)),
            ],
        ),
    ]
